version: '0.0.6'
name: chat2llms
services:
  backend:
    image: chat2llms:0.0.6
    container_name: chat2llms
    ports:
      - "8000:8000"
      - "6006:6006"
      - "8501:8501"
    volumes:
      - ${DATA_PATH}/sqlite:/code/sqlite
      - ${EMBEDDING_MODEL_PATH}:/BigModels/360Zhinao-search
    depends_on:
      - qdrant
    environment:
      - EMBEDDING_MODEL_PATH=/BigModels/360Zhinao-search
      - DB_SQLITE_PATH=/code/sqlite/chat2llms.db
      - QRANT_HOST=qdrant
      - QRANT_PORT=6333
      - OLLAMA_URL=${OLLAMA_URL}
    networks:
      - my-network

  qdrant:
    image: qdrant/qdrant
    
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ${DATA_PATH}\qdrant_storage:/qdrant/storage
    networks:
      - my-network
networks:
  my-network:
    driver: bridge