version: '0.0.3'
services:
  backend:
    build: ..
    ports:
      - "8000:8000"
    volumes:
      - ../data/sqlite:/code/sqlite
      - ../BigModels:/BigModels
      
    environment:
      - MODEL_PATH=/BigModels/360Zhinao-search
      - DB_SQLITE_PATH=/code/sqlite/chat2llms.db

  vector_db:
    image: qdrant/qdrant
    container_name: qdrant_htw
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ../data/qdrant_storage:/qdrant/storage