name: chat2llms
services:
  backend:
    image: chat2llms:latest
    container_name: chat2llms
    ports:
      - "8000:8000"
      - "6006:6006"
      - "8501:8501"
    volumes:
      - ${EMBEDDING_MODEL_PATH}:/BigModels/360Zhinao-search
    depends_on:
      - qdrant
    environment:
      - EMBEDDING_MODEL_PATH=/BigModels/360Zhinao-search
      - QRANT_HOST=qdrant
      - MYSQL_HOST=mysql
    env_file:
      - .env
    networks:
      - my-network
    restart: always

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ${DATA_PATH}/qdrant_storage:/qdrant/storage
    networks:
      - my-network
    restart: always

  mysql:
    image: mysql:9.0
    container_name: chatbot_mysql
    ports:
      - "3306:3306"
    volumes:
      - ${DATA_PATH}/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - my-network
    restart: always
networks:
  my-network:
    driver: bridge